services:
  php:
    build:
      context: .
    volumes:
      - .:/app:delegated
    secrets:
      - source: ssh_private_key
        target: /root/.ssh/id_rsa
      - source: ssh_known_hosts
        target: /root/.ssh/known_hosts
    environment:
      XDEBUG_CLIENT_HOST: host.docker.internal
      PHP_IDE_CONFIG: "serverName=php_matcher"
    ports:
      - "5022:22"

secrets:
  ssh_private_key:
    file: ~/.ssh/id_rsa
  ssh_known_hosts:
    file: ~/.ssh/known_hosts
